[package]
name = "manage"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
git2 = "0.20.2"
handlebars = "6.3.1"
thiserror = "2.0.12"
toml = "0.8.23"
